version: 1
formatters:
  mustsee:
    format: '>>> %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'
  test:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'
handlers:
  consoleEverything:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  consoleWarningOrWorse:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  consoleMustSee:
    class: logging.StreamHandler
    level: DEBUG
    formatter: mustsee
    stream: ext://sys.stdout
loggers:
  cewe2pdf.config:
    handlers: [consoleWarningOrWorse]
    level: DEBUG
    propagate: no
  cewe2pdf.mustsee:
    level: INFO
    handlers: [consoleMustSee]
    propagate: no
  cewe2pdf.test:
    level: INFO
    handlers: [consoleWarningOrWorse]
    propagate: no
  PIL.PngImagePlugin:
    level: WARNING
    handlers: [consoleEverything]
    propagate: no
root:
  level: INFO
  handlers: [consoleEverything]